name: Create release
on:
  release:
    types: [created]
jobs:
  release_info:
    runs-on: windows-latest
    outputs:
      tag_name: ${{ steps.get_release_info.outputs.tag_name }}
      prerelease: ${{ steps.get_release_info.outputs.prerelase }}
    steps:
    - name: Get Release Info
      id: get_release_info
      run: |
        $tag_name = "${{ github.ref_name }}"
        $prerelease = 'false'
        if ($tag_name -like '*-auto' || $tag_name -like '*-RC') {
          $prerelease = 'true'
        }
        echo "::set-output name=prerelease::${prerelease}"
        echo "::set-output name=tag_name::${tag_name}"
  create_release:
    runs-on: windows-latest
    needs: release_info
    steps:
    - name: Print info
      run: echo "${{needs.release_info.outputs.tag_name}} is a ${{needs.release_info.outputs.prerelease}}"
  
