name: Create release
on:
  release:
    types: [created]
jobs:
  release_info:
    runs-on: windows-latest
    outputs:
      tag_name: ${{ steps.get_tag_name.outputs.tag_name }}
      is_prerelease: ${{ steps.get_prerelease.outputs.is_prerelease }}
    steps:
    - name: Get Tag Name
      id: get_tag_name
      run: |
        $tag_name = "${{ github.ref_name }}"
        echo "::set-output name=tag_name::${tag_name}"
    - name: Get is Prerelease
      id: get_prerelease
      run: |
        $tag_name = "${{ github.ref_name }}"
        $is_prerelease = 'Pepito'
        if($tag_name -like '*-auto' || $tag_name -like '*-RC') {
          $is_prerelease = 'Juanito'
        }
        echo "::set-output name=is_prerelease::${is_prerelease}"
  create_release:
    runs-on: windows-latest
    needs: release_info
    steps:
    - name: Print info
      run: echo "${{needs.release_info.outputs.tag_name}} is a ${{needs.release_info.outputs.is_prerelease}}"
